### ISSUE TITLE
We should support token based auth, especially for web sockets

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-passport#2]
I think we should use https://github.com/themikenicholson/passport-jwt under the hood.

**Comment by chrismbeckett** [comment]
Completely agree. And it would be useful if the docs for Feathers actually showed how to "Manually setting up shared authentication between websockets and an HTTP REST API can be tricky" so that in the end you can actually setup authentication how you like.

**Comment by ekryski** [comment]
@chrismbeckett thanks for the feedback. We will be rolling out some new docs within the week. We'll have a section on authentication that will hopefully show a clear enough example. I'll bug you for more feedback when it's up.

**Comment by daffl** [comment]
Can't we just link to a good guide how to do it manually? We already do have a full guide how to set everything up with feathers-passport including sessions and user storage but it will indeed be more digestible on the new homepage.

:+1: on the tokens though

**Comment by chrismbeckett** [comment]
@ekryski Thanks for the update, and look forward to that. I like the stuff done by the Auth0 guys and I prefer to use tokens over cookies and sessions for my api, which I think is where the wind is blowing if you are building a stand-alone API rather than an integrated application.

**Comment by marshallswain** [comment]
This is done here: https://www.npmjs.com/package/feathers-passport-jwt

**Comment by daffl** [comment]
I talked with @marshallswain and we are thinking of dropping the session based `feathers-passport` for Feathers 2. This means `feathers-passport-jwt` will become `feathers-passport` (1.0) which will then be used by the full-fledged `feathers-authentication`. That way everybody will have to use JWT + Passport - which I think is fine since JWT is easy to implement and much more secure.

**Comment by daffl** [comment]
Work is now being done in https://github.com/feathersjs/feathers-authentication/
