### ISSUE TITLE
JWT authentication

### ISSUE THREAD

**Issue by cleechtech** [feathersjs/feathers-passport#5]
I am new to the feather.js community. For authentication with express I've used JWT in the past. It seems like a better approach to use tokens instead of sessions for authentication. Does feather.js support jwt authentication? Are there examples or tutorials anywhere? (happy to help make some if they don't exist atm)

**Comment by marshallswain** [comment]
This is the same as #2.  @daffl Can you create a `feathers-passport-jwt` repo and give me access?

**Comment by daffl** [comment]
Do you have a link how the configuration works? I assume you'd use passport to obtain the token and then the token to communicate right? `feathers-passport-jwt` probably makes sense then.

I'm thinking of finally finishing the `feathers-authentication` plugin which could wrap this as well.

**Comment by cleechtech** [comment]
I made this repo that does JWT auth with express and angular: https://github.com/cleechtech/node-jwt-intro

Draws heavily from the [scotch tutorial](https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens) and [egghead series](https://egghead.io/series/angularjs-authentication-with-jwt)

**Comment by marshallswain** [comment]
@daffl I have finished with the feathers-passport-jwt plugin.  Just adding tests.

**Comment by daffl** [comment]
Oh sweet! You should be allowed to create new repositories. Looking forward to it!

**Comment by marshallswain** [comment]
It says I don't have sufficient permission to create repositories in FeathersJS.

**Comment by daffl** [comment]
I updated the settings. Can you try again?

**Comment by marshallswain** [comment]
@daffl that worked.  Thanks.
